### ISSUE TITLE
Use named export

### ISSUE THREAD

**Issue by Kelin2025** [alik0211/hardtack#47]
Now there is `export default` with 3 functions. 
I guess better have 3 exports instead, it may save some bytes with tree-shaking if some of functions are not used.

**Comment by plesiecki** [comment]
yes, please 🙏

**Comment by alik0211** [comment]
Made in version 5.0.1 🎉

**Comment by plesiecki** [comment]
Hello 👋 Looks like API is still exposed only as default export 🤔

**Comment by alik0211** [comment]
@plesiecki examples in the [Usage](https://github.com/alik0211/hardtack#usage) section. What's wrong with the default export?

**Comment by plesiecki** [comment]
default isn't tree-shakeable if I use just a single function

**Comment by plesiecki** [comment]
oh cool, I see, now you can import just a single function, that's good 👍
